### ISSUE TITLE
Resolve *.figma.js files

### ISSUE THREAD

**Issue by macintoshhelper** [react-figma/webpack-config#1]
`figma.tsx` and `.figma.ts` doesn't handle the case of dependencies (such as React Primitives) that don't bundle TypeScript source (where the dist is `index.figma.js`).

https://github.com/react-figma/webpack-config/blob/master/index.js#L31

```js
    resolve: { extensions: ['.figma.tsx', '.figma.ts','.tsx', '.ts', '.jsx', '.js'] },
```

**TO ->**

```js
    resolve: { extensions: ['.figma.tsx', '.figma.ts', 'figma.jsx', '.figma.js', '.tsx', '.ts', '.jsx', '.js'] },
```

Should I go ahead and open a PR?

**Related issues:**

> https://github.com/react-figma/react-figma/issues/11

**Comment by ilyalesik** [comment]
Yes, that makes sense! Please, send PR. 🙌
